import {
  WORD_PICKER_ALL_SPOKE_PATHS,
  WORD_PICKER_ALIAS_REDIRECTS,
} from "../lib/word-picker-wheel-spokes"

const paths = new Set([
  ...WORD_PICKER_ALL_SPOKE_PATHS,
  ...WORD_PICKER_ALIAS_REDIRECTS.map((a) => a.source),
  "/spin-word-picker-wheel",
  "/what-should-i-draw",
])

type Row = [string, string, string[]]

const checks: Row[] = [
  ["3", "Common Words", ["/common-words-wheel"]],
  ["3", "Easy Words", ["/easy-words-wheel"]],
  ["3", "Random Words", ["/random-words-wheel"]],
  ["3", "Funny Words", ["/funny-words-wheel"]],
  ["3", "Weird Words", ["/weird-words-wheel"]],
  ["3", "Difficult Words", ["/difficult-words-wheel"]],
  ["3", "Long Words", ["/long-words-wheel"]],
  ["3", "Short Words", ["/short-words-wheel"]],
  ["3", "Positive Words", ["/positive-words-wheel"]],
  ["3", "Negative Words", ["/negative-words-wheel"]],
  ["3", "Action Words", ["/action-word-wheel", "/action-words-wheel"]],
  ["3", "Descriptive Words", ["/descriptive-words-wheel"]],
  ["3", "Nouns", ["/noun-word-wheel"]],
  ["3", "Verbs", ["/verb-word-wheel"]],
  ["3", "Adjectives", ["/adjective-word-wheel"]],
  ["3", "Adverbs", ["/adverb-word-wheel"]],
  ["3", "Opposite Words", ["/opposite-words-wheel"]],
  ["3", "Rhyming Words", ["/rhyming-words-wheel"]],
  ["3", "Compound Words", ["/compound-words-wheel"]],
  ["3", "Sight Words", ["/sight-word-picker", "/sight-words-wheel"]],
  ["3", "Vocabulary Words", ["/vocabulary-word-wheel", "/vocabulary-words-wheel"]],
  ["4", "Random Word Generator", ["/random-word-generator", "/spin-word-picker-wheel"]],
  ["4", "Writing Prompt Word Wheel", ["/writing-prompt-word-wheel"]],
  ["4", "Story Word Generator", ["/story-word-generator"]],
  ["4", "Random Story Words", ["/random-story-words-wheel"]],
  ["4", "Character Word Picker", ["/character-word-picker"]],
  ["4", "Setting Word Picker", ["/setting-word-picker"]],
  ["4", "Plot Word Generator", ["/plot-word-generator"]],
  ["4", "Story Starter Wheel", ["/story-starter-word-wheel"]],
  ["4", "Creative Writing Wheel", ["/creative-writing-word-wheel"]],
  ["4", "Fiction Writing Word Wheel", ["/fiction-writing-word-wheel"]],
  ["4", "Random Writing Challenge", ["/random-writing-challenge-wheel"]],
  ["4", "Poetry Word Picker", ["/poetry-word-picker"]],
  ["4", "Poetry Challenge Wheel", ["/poetry-challenge-word-wheel"]],
  ["4", "Songwriting Word Generator", ["/songwriting-word-generator"]],
  ["4", "Random Theme Generator", ["/random-theme-word-wheel"]],
  ["4", "Random Topic Generator", ["/random-topic-word-wheel"]],
  ["4", "Brainstorming Word Wheel", ["/brainstorming-word-wheel"]],
  ["5", "Classroom Word Picker", ["/classroom-word-picker"]],
  ["5", "Random Vocabulary Word", ["/random-vocabulary-word-wheel"]],
  ["5", "Vocabulary Wheel", ["/vocabulary-word-wheel"]],
  ["5", "Spelling Word Wheel", ["/spelling-word-wheel"]],
  ["5", "Sight Word Picker", ["/sight-word-picker"]],
  ["5", "Reading Word Picker", ["/reading-word-picker"]],
  ["5", "Writing Word Picker", ["/classroom-writing-word-picker"]],
  ["5", "Random Student Vocabulary", ["/student-vocabulary-word-wheel"]],
  ["5", "Word-of-the-Day Wheel", ["/word-of-the-day-wheel"]],
  ["5", "English Practice Wheel", ["/english-practice-word-wheel"]],
  ["5", "ESL Word Wheel", ["/esl-word-wheel"]],
  ["5", "Language Learning Wheel", ["/language-learning-word-wheel"]],
  ["5", "Classroom Discussion Word", ["/classroom-discussion-word-wheel"]],
  ["5", "Random Topic Word", ["/classroom-topic-word-wheel"]],
  ["5", "Homework Word Picker", ["/homework-word-picker"]],
  ["6", "Word Challenge", ["/word-challenge-wheel"]],
  ["6", "Guess the Word", ["/guess-the-word-wheel"]],
  ["6", "Describe the Word", ["/describe-the-word-wheel"]],
  ["6", "Act Out the Word", ["/act-out-the-word-wheel"]],
  ["6", "Draw the Word", ["/draw-the-word-wheel"]],
  ["6", "Pictionary Word Wheel", ["/pictionary-word-wheel"]],
  ["6", "Charades Word Wheel", ["/charades-word-wheel"]],
  ["6", "Taboo Word Generator", ["/taboo-word-generator"]],
  ["6", "Word Association Game", ["/word-association-wheel"]],
  ["6", "Word Chain Game", ["/word-chain-wheel"]],
  ["6", "Forbidden Word Challenge", ["/forbidden-word-challenge-wheel"]],
  ["6", "Random Word Challenge", ["/random-word-challenge-wheel"]],
  ["6", "Speed Word Challenge", ["/speed-word-challenge-wheel"]],
  ["6", "Last Letter Challenge", ["/last-letter-word-challenge"]],
  ["6", "First Letter Challenge", ["/first-letter-word-challenge"]],
  ["6", "Word Battle", ["/word-battle-wheel"]],
  ["7", "Random Drawing Word", ["/random-drawing-word-wheel"]],
  ["7", "What Should I Draw?", ["/what-should-i-draw", "/what-word-should-i-draw"]],
  ["7", "Drawing Prompt Wheel", ["/drawing-prompt-word-wheel"]],
  ["7", "Art Prompt Generator", ["/art-prompt-word-generator"]],
  ["7", "Sketch Challenge", ["/sketch-challenge-word-wheel"]],
  ["7", "Doodle Word Generator", ["/doodle-word-generator"]],
  ["7", "Character Drawing Prompt", ["/character-drawing-word-wheel"]],
  ["7", "Animal Drawing Wheel", ["/animal-drawing-word-wheel"]],
  ["7", "Object Drawing Wheel", ["/object-drawing-word-wheel"]],
  ["7", "Fantasy Drawing Prompt", ["/fantasy-drawing-word-wheel"]],
  ["7", "Random Art Challenge", ["/random-art-challenge-word-wheel"]],
  ["7", "Inktober Word Wheel", ["/inktober-word-wheel"]],
  ["8", "Random Speaking Topic", ["/random-speaking-topic-wheel"]],
  ["8", "Speaking Challenge", ["/speaking-challenge-word-wheel"]],
  ["8", "Conversation Word Wheel", ["/conversation-word-wheel"]],
  ["8", "Debate Topic Generator", ["/debate-topic-word-wheel"]],
  ["8", "Public Speaking Word Picker", ["/public-speaking-word-picker"]],
  ["8", "Impromptu Speaking Wheel", ["/impromptu-speaking-word-wheel"]],
  ["8", "Acting Prompt Wheel", ["/acting-prompt-word-wheel"]],
  ["8", "Charades Word Generator", ["/charades-word-generator"]],
  ["8", "Acting Challenge", ["/acting-challenge-word-wheel"]],
  ["8", "Describe This Word", ["/describe-this-word-wheel"]],
  ["8", "Explain the Random Word", ["/explain-the-random-word-wheel"]],
  ["8", "60-Second Speaking Challenge", ["/60-second-speaking-challenge-wheel"]],
  ["10", "Noun Wheel", ["/noun-word-wheel"]],
  ["10", "Verb Wheel", ["/verb-word-wheel"]],
  ["10", "Adjective Wheel", ["/adjective-word-wheel"]],
  ["10", "Adverb Wheel", ["/adverb-word-wheel"]],
  ["10", "Action Word Wheel", ["/action-word-wheel", "/action-words-wheel"]],
  ["10", "Describing Word Wheel", ["/describing-word-wheel"]],
  ["10", "Feeling Word Wheel", ["/feeling-word-wheel"]],
  ["10", "Emotion Word Wheel", ["/emotion-word-wheel"]],
  ["10", "Animal Word Wheel", ["/animal-word-wheel", "/animal-words-wheel"]],
  ["10", "Food Word Wheel", ["/food-word-wheel", "/food-words-wheel"]],
  ["10", "Object Word Wheel", ["/object-word-wheel"]],
  ["10", "Place Word Wheel", ["/place-word-wheel"]],
  ["10", "Person Word Wheel", ["/person-word-wheel"]],
  ["10", "Nature Word Wheel", ["/nature-word-wheel", "/nature-words-wheel"]],
  ["10", "Fantasy Word Wheel", ["/fantasy-word-wheel", "/fantasy-words-wheel"]],
  ["11", "Easy Words", ["/easy-words-wheel"]],
  ["11", "Beginner Words", ["/beginner-words-wheel"]],
  ["11", "Intermediate Words", ["/intermediate-words-wheel"]],
  ["11", "Advanced Words", ["/advanced-words-wheel"]],
  ["11", "Difficult Words", ["/difficult-words-wheel"]],
  ["11", "Challenging Words", ["/challenging-words-wheel"]],
  ["11", "Rare Words", ["/rare-words-wheel"]],
  ["11", "Unusual Words", ["/unusual-words-wheel"]],
  ["11", "Obscure Words", ["/obscure-words-wheel"]],
  ["11", "Long Words", ["/long-words-wheel"]],
  ["11", "Short Words", ["/short-words-wheel"]],
  ...("abcdefghijklmnopqrstuvwxyz".split("").map(
    (l): Row => [
      "12",
      `Words Starting With ${l.toUpperCase()}`,
      [`/words-starting-with-${l}`],
    ],
  )),
  ["12", "Random A–Z Word", ["/random-a-z-word-wheel"]],
  ["12", "Random Word by Letter", ["/random-word-by-letter"]],
  ["12", "Word Ending Letter Picker", ["/word-ending-letter-picker"]],
  ["12", "Words With 3 Letters", ["/words-with-3-letters", "/3-letter-words-wheel"]],
  ["12", "4-Letter Word Wheel", ["/4-letter-words-wheel"]],
  ["12", "5-Letter Word Wheel", ["/5-letter-words-wheel"]],
  ["12", "6-Letter Word Wheel", ["/6-letter-words-wheel"]],
  ["12", "Long Word Generator", ["/long-word-generator", "/long-words-wheel"]],
  ["13", "2-Letter Words", ["/2-letter-words-wheel"]],
  ["13", "3-Letter Words", ["/3-letter-words-wheel"]],
  ["13", "4-Letter Words", ["/4-letter-words-wheel"]],
  ["13", "5-Letter Words", ["/5-letter-words-wheel"]],
  ["13", "6-Letter Words", ["/6-letter-words-wheel"]],
  ["13", "7-Letter Words", ["/7-letter-words-wheel"]],
  ["13", "8-Letter Words", ["/8-letter-words-wheel"]],
  ["13", "9-Letter Words", ["/9-letter-words-wheel"]],
  ["13", "10-Letter Words", ["/10-letter-words-wheel"]],
  ["13", "Longest Words", ["/longest-words-wheel"]],
  ["13", "Random Long Word", ["/random-long-word-wheel"]],
  ["14", "Kids Word Wheel", ["/kids-word-wheel"]],
  ["14", "Easy Word Wheel", ["/kids-easy-word-wheel", "/easy-words-wheel"]],
  ["14", "Kids Vocabulary Wheel", ["/kids-vocabulary-word-wheel"]],
  ["14", "Animal Word Wheel", ["/kids-animal-word-wheel", "/animal-word-wheel"]],
  ["14", "Food Word Wheel", ["/kids-food-word-wheel", "/food-word-wheel"]],
  ["14", "Color Word Wheel", ["/kids-color-word-wheel"]],
  ["14", "School Word Wheel", ["/kids-school-word-wheel", "/school-words-wheel"]],
  ["14", "Funny Word Wheel", ["/kids-funny-word-wheel", "/funny-words-wheel"]],
  ["14", "Kids Drawing Word Wheel", ["/kids-drawing-word-wheel"]],
  ["14", "Kids Story Word Generator", ["/kids-story-word-generator"]],
  ["14", "Kids Charades Wheel", ["/kids-charades-word-wheel"]],
  ["14", "Kids Pictionary Wheel", ["/kids-pictionary-word-wheel"]],
  ["14", "Preschool Word Wheel", ["/preschool-word-wheel"]],
  ["15", "Funny Word Wheel", ["/funny-words-wheel"]],
  ["15", "Party Word Generator", ["/party-word-generator"]],
  ["15", "Charades Wheel", ["/charades-wheel", "/charades-word-wheel"]],
  ["15", "Pictionary Wheel", ["/pictionary-wheel", "/pictionary-word-wheel"]],
  ["15", "Acting Word Wheel", ["/acting-word-wheel"]],
  ["15", "Random Conversation Word", ["/random-conversation-word-wheel"]],
  ["15", "Icebreaker Word Wheel", ["/icebreaker-word-wheel"]],
  ["15", "Party Challenge Word", ["/party-challenge-word-wheel"]],
  ["16", "Animal Words", ["/animal-words-wheel"]],
  ["16", "Food Words", ["/food-words-wheel"]],
  ["16", "Movie Words", ["/movie-words-wheel"]],
  ["16", "Sports Words", ["/sports-words-wheel"]],
  ["16", "Travel Words", ["/travel-words-wheel"]],
  ["16", "Nature Words", ["/nature-words-wheel"]],
  ["16", "School Words", ["/school-words-wheel"]],
  ["16", "Christmas Words", ["/christmas-words-wheel"]],
  ["16", "Halloween Words", ["/halloween-words-wheel"]],
  ["16", "Thanksgiving Words", ["/thanksgiving-words-wheel"]],
  ["16", "Valentine's Words", ["/valentines-words-wheel"]],
  ["16", "Summer Words", ["/summer-words-wheel"]],
  ["16", "Winter Words", ["/winter-words-wheel"]],
  ["16", "Fantasy Words", ["/fantasy-words-wheel"]],
  ["16", "Science Words", ["/science-words-wheel"]],
  ["16", "Space Words", ["/space-words-wheel"]],
  ["16", "Ocean Words", ["/ocean-words-wheel"]],
  ["16", "Dinosaur Words", ["/dinosaur-words-wheel"]],
  ["16", "Pokémon Words", ["/pokemon-words-wheel"]],
  ["16", "Minecraft Words", ["/minecraft-words-wheel"]],
  ["16", "Fortnite Words", ["/fortnite-words-wheel"]],
  ["19", "/word-picker-wheel", ["/word-picker-wheel"]],
  ["19", "/random-word-generator", ["/random-word-generator"]],
  ["19", "/random-word-picker", ["/random-word-picker"]],
  ["19", "/random-word-wheel", ["/random-word-wheel"]],
  ["19", "/random-word-spinner", ["/random-word-spinner"]],
  ["19", "/word-spinner", ["/word-spinner"]],
  ["19", "/word-generator-wheel", ["/word-generator-wheel"]],
  ["19", "/random-word-selector", ["/random-word-selector"]],
  ["19", "/random-word-generator-online", ["/random-word-generator-online"]],
  ["20", "for Writing", ["/random-word-generator-for-writing"]],
  ["20", "for Stories", ["/random-word-generator-for-stories"]],
  ["20", "for Drawing", ["/random-word-generator-for-drawing"]],
  ["20", "for Pictionary", ["/random-word-generator-for-pictionary"]],
  ["20", "for Charades", ["/random-word-generator-for-charades"]],
  ["20", "for Games", ["/random-word-generator-for-games"]],
  ["20", "for Kids", ["/random-word-generator-for-kids"]],
  ["20", "for Students", ["/random-word-generator-for-students"]],
  ["20", "for Teachers", ["/random-word-generator-for-teachers"]],
  ["20", "for ESL", ["/random-word-generator-for-esl"]],
  ["20", "Vocab Generator", ["/random-vocabulary-word-generator"]],
  ["20", "Writing Prompt Gen", ["/random-writing-prompt-generator"]],
  ["20", "Story Word Gen", ["/random-story-word-generator"]],
  ["20", "Drawing Word Gen", ["/random-drawing-word-generator"]],
  ["20", "Speaking Topic Gen", ["/random-speaking-topic-generator"]],
  ["20", "Acting Prompt Gen", ["/random-acting-prompt-generator"]],
  ["21", "What Word Should I Pick?", ["/what-word-should-i-pick"]],
  ["21", "Pick a Random Word", ["/pick-a-random-word"]],
  ["21", "Give Me a Random Word", ["/give-me-a-random-word"]],
  ["21", "What Random Word Should I Use?", ["/what-random-word-should-i-use"]],
  ["21", "What Word Should I Draw?", ["/what-word-should-i-draw"]],
  ["21", "What Should I Draw?", ["/what-should-i-draw"]],
  ["21", "What Word Should I Write About?", ["/what-word-should-i-write-about"]],
  ["21", "What Should I Write About?", ["/what-should-i-write-about"]],
  ["21", "What Word Should I Use in My Story?", ["/what-word-should-i-use-in-my-story"]],
  ["21", "What Word Should I Act Out?", ["/what-word-should-i-act-out"]],
  ["21", "What Word Should I Describe?", ["/what-word-should-i-describe"]],
  ["21", "What Word Should I Use for a Story?", ["/what-word-should-i-use-for-a-story"]],
  ["21", "What Word Should I Use for a Poem?", ["/what-word-should-i-use-for-a-poem"]],
  ["21", "What Word Should I Use for Pictionary?", ["/what-word-should-i-use-for-pictionary"]],
  ["21", "What Word Should I Use for Charades?", ["/what-word-should-i-use-for-charades"]],
  ["21", "Give Me 3 Random Words", ["/give-me-3-random-words"]],
  ["21", "Give Me 5 Random Words", ["/give-me-5-random-words"]],
  ["21", "Give Me a Random Writing Prompt", ["/give-me-a-random-writing-prompt"]],
]

const missing: { section: string; topic: string; tried: string[] }[] = []
const present: { section: string; topic: string; hit: string }[] = []

for (const [section, topic, urls] of checks) {
  const hit = urls.find((u) => paths.has(u))
  if (hit) present.push({ section, topic, hit })
  else missing.push({ section, topic, tried: urls })
}

const bySection: Record<string, number> = {}
for (const m of missing) bySection[m.section] = (bySection[m.section] || 0) + 1

console.log(
  JSON.stringify(
    {
      totalSpokes: WORD_PICKER_ALL_SPOKE_PATHS.length,
      checked: checks.length,
      present: present.length,
      missingCount: missing.length,
      missingBySection: bySection,
      missing,
    },
    null,
    2,
  ),
)
